// <auto-generated />
using System;
using ChainGuard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChainGuard.Data.Migrations
{
    [DbContext(typeof(ChainGuardDbContext))]
    partial class ChainGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ChainGuard.Data.Entities.BlockEntity", b =>
                {
                    b.Property<Guid>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BlockId");

                    b.HasIndex("BlockHeight")
                        .HasDatabaseName("IX_Blocks_BlockHeight");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("IX_Blocks_ChainId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_Blocks_Timestamp");

                    b.HasIndex("ChainId", "BlockHeight")
                        .IsUnique()
                        .HasDatabaseName("IX_Blocks_ChainId_BlockHeight");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.ChainEntity", b =>
                {
                    b.Property<Guid>("ChainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenesisBlockId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LatestBlockId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChainId");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.OffChainDataEntity", b =>
                {
                    b.Property<Guid>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.HasKey("DataId");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("IX_OffChainData_BlockId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OffChainData_CreatedAt");

                    b.HasIndex("DataType")
                        .HasDatabaseName("IX_OffChainData_DataType");

                    b.ToTable("OffChainData");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.BlockEntity", b =>
                {
                    b.HasOne("ChainGuard.Data.Entities.ChainEntity", "Chain")
                        .WithMany("Blocks")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.OffChainDataEntity", b =>
                {
                    b.HasOne("ChainGuard.Data.Entities.BlockEntity", "Block")
                        .WithMany("OffChainData")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.BlockEntity", b =>
                {
                    b.Navigation("OffChainData");
                });

            modelBuilder.Entity("ChainGuard.Data.Entities.ChainEntity", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
